### ISSUE TITLE
 generated an exception

### ISSUE THREAD

**Issue by EduBRz** [ItzAmirreza/EzChestShop#2]
When you access the shop's gui and generate this error

https://pastebin.com/p548rmEk

purpurclip-1.17.1-1265

**Comment by ItzAmirreza** [comment]
Hey there,
Thanks for your report. I'll check this ASAP.
Also, please tell me wether you have installed protocollib or not.
Thank you.

**Comment by EduBRz** [comment]
ProtocolLib v4.7.0

**Comment by ItzAmirreza** [comment]
got fixed by itself?

**Comment by EduBRz** [comment]
No, I'm using another plugin while fixing your plugins 
I'm using this https://github.com/syake4659/ChestShop
