### ISSUE TITLE
Player Only Can Create 1 Shop

### ISSUE THREAD

**Issue by aril3721** [ItzAmirreza/EzChestShop#26]
Hello Sir. I Dont Know Why My Member Only Can Create 1 Shop. 
![image](https://user-images.githubusercontent.com/67541360/143409183-2deb72fb-9bc4-4f12-a99c-914ba31a76c5.png)

im not enable permission in config.yml!

And Im Using Griefprevention

**Comment by aril3721** [comment]
Update: EzChestShop Get Blocked By My Anti Cheat (NoCheatPlus.) And I Fixed Now. But Why
![image](https://user-images.githubusercontent.com/67541360/143413515-0335c021-8851-41b3-ac4a-aa84885a56fe.png)
appear randomly. if my player execute cmd /ecs create 1 1

**Comment by ElitoGame** [comment]
With the latest versions of EzChestShop, we've added WorldGuard custom Flags for disabling Shop creation. Are you sure, you haven't modified any of these: https://media.discordapp.net/attachments/756258510580220047/913358640587624448/Screenshot_572.png

**Comment by aril3721** [comment]
> With the latest versions of EzChestShop, we've added WorldGuard custom Flags for disabling Shop creation. Are you sure, you haven't modified any of these: https://media.discordapp.net/attachments/756258510580220047/913358640587624448/Screenshot_572.png

Nah, i dont edit any worldguard flag. in my main survival world

**Comment by ItzAmirreza** [comment]
I think this problem had happened for people that were using WorldGuard and upgrading to 1.4.4, the default value of these flags were to not give them ability to create chest shops(by default it was preventing), so I guess if you try allowing shop creation flag here, it would work. (even though you didn't touch it, by default I assume it's denied)

Looking forward to see if that fixes your problem.

**Comment by aril3721** [comment]
> 

ok i will try that

**Comment by aril3721** [comment]
![image](https://user-images.githubusercontent.com/67541360/143430997-3db668c3-7aaf-41d8-b8de-30a0f740d248.png)
i set my GLOBAL flag to like that. but same problem. when i create/remove randomly appear cant create shop in this location

**Comment by ItzAmirreza** [comment]
I'll investigate this issue this coming weekend.

**Comment by ItzAmirreza** [comment]
I guess we can assume the problem is fixed?
