### ISSUE TITLE
Update Notify issues

### ISSUE THREAD

**Issue by TheWylot** [ItzAmirreza/EzChestShop#47]
currently using 1.5.6 but getting Update Notify with this title: 1.5.6 OMG MEGA UPDATE!

**Comment by ElitoGame** [comment]
That's because @ItzAmirreza sometimes names the updates with hype messages rather then following the x.y.z standard. Should be fixed simple enough by just renaming stuff over on Spigot.

**Comment by ItzAmirreza** [comment]
Will remember not to have hype messages in plugin version
