### ISSUE TITLE
people cant buy or sell from my shop

### ISSUE THREAD

**Issue by OMKOAKRE12** [ItzAmirreza/EzChestShop#49]
pls help me

**Comment by ElitoGame** [comment]
Hey! We'll need a bit more info to support you:
Are you using Vault AND an Economy plugin or XP based economy?

What version if ECS are you using?

Are there any errors in the console?


Also feel free to look around our discord, we've helped a bunch of playin the past and maybe you'll already find your solution in #support :)

**Comment by ItzAmirreza** [comment]
No info provided, no response as well.
