### ISSUE TITLE
Issue with hologram

### ISSUE THREAD

**Issue by kaimokene** [ItzAmirreza/EzChestShop#55]
Hello, i seem to have a problem regarding holograms.

Breaking and placing the shop at the same spot will retain the hologram item of the old shop. Video so you could understand better. Restarting the server seems to fix broken ones: https://streamable.com/kd6yvw

Using: EzChestShop-1.6.4
MC Version: 1.20.1

**Comment by ElitoGame** [comment]
Hey this bug has been fixed in this pre-release: https://hangar.papermc.io/ItzAmirreza/EzChestShop/versions/1.6.4.3
Your video doesn't seem related to holograms at all, it shows a sign crashing your client, is that another bug or not related?

**Comment by kaimokene** [comment]
blame 5 hours of sleep lmao. Sent the wrong video. Will test out this build tomorrow and then close this issue if that fixes it

**Comment by kaimokene** [comment]
Works now, thanks for the fast response
