### ISSUE TITLE
folia support

### ISSUE THREAD

**Issue by cgw2023** [ItzAmirreza/EzChestShop#61]
please add folia support to this plugin. It is the latest branch of Minecraft server developed by the team of papermc which targeted for super large servers
https://github.com/PaperMC/Folia

**Comment by XiroInfinity** [comment]
I'm confused what folia does that would prevent this plugin from being supported as is? It's a fork of paper, and this works on paper.

**Comment by cgw2023** [comment]
> Added

Thank you so much, would you please also upload a jar version to modrinth or paperhanger so that people can use?
